### ISSUE TITLE
字数统计功能

### ISSUE THREAD

**Issue by jxjxjhjh** [Hansanshi/mark-idea#10]
编辑器本身支持字数统计，但是markidea现在还没有，希望能加上。
另外，我在vscode里面使用v编辑器插件的时候，看到的字数统计好像只是全文所有字数，没有”选中内容“的字数统计。
有个需求，就是除了全文字数统计之外，希望能更详细一点，以下两种方式都可以
1、选中内容字数统计（这个在md编辑器中比较常见了）
2、大纲条目后面的字数统计（这个在任何通用编辑器中从未见过，但在小说写作软件中都有，我就是写小说，所以希望如果不难实现最好能实现这种字数统计方式）

**Comment by Hansanshi** [comment]
字数统计可以加上，配置下就好

但你说的后面两点，建议到vditor提个issue，在编辑器级别实现更方便

**Comment by jxjxjhjh** [comment]
好的

**Comment by jxjxjhjh** [comment]
> 字数统计可以加上，配置下就好
> 
> 但你说的后面两点，建议到vditor提个issue，在编辑器级别实现更方便

可是vditor本身就有字数统计功能吧？我在用vditor的vscode插件中还是思源笔记这种都有字数统计啊。

**Comment by Hansanshi** [comment]
我说的是 1. 选中字数统计；2.按大纲条目统计字数  这两点vditor没有。

vditor本身确实是支持字数统计，不过是只支持全文的字数。

**Comment by jxjxjhjh** [comment]
> 我说的是 1. 选中字数统计；2.按大纲条目统计字数 这两点vditor没有。
> 
> vditor本身确实是支持字数统计，不过是只支持全文的字数。

哦哦，明白了。

**Comment by Hansanshi** [comment]
仅支持全文字数统计，见新版本
