### ISSUE TITLE
公开笔记页面无法通过跳转访问

### ISSUE THREAD

**Issue by jxjxjhjh** [Hansanshi/mark-idea#12]
之前提过这个问题。
比如我有一篇公开笔记，我使用301跳转或者反代等方式，将主域名跳转过来当做主页，但设置好后访问主域名却会进入登录界面。
一开始我以为是我设置问题，但实际上同样的方法跳转任何其他网页都没问题，所以我想到一个可能。
markidea的设定中可能有什么检查，在直接访问公开页面的时候不会触发，跳转过来则会触发，导致无法通过跳转方式访问公开笔记页面。
例如 191954.xyz 这个域名我已经设置好跳转一篇公开笔记了，但只会访问登录界面。
而 mail.191954.xyz 这个域名就可以正常跳转到阿里云邮箱。

**Comment by Hansanshi** [comment]
我记得我回复过你在这个issue #6 

是你配置有问题，我配置的跳转就没问题

你可以试试下边这个我配置的链接，可以正常跳转你的公开笔记

http://pptvector.sanshicloud.cn

**Comment by jxjxjhjh** [comment]
我用的是caddy1.0版
191954.xyz:80 {
    redir https://note.191954.xyz/#/article/191954/2{url}
}
这个方法跳转别的可以
问题是不是出在链接中的 /#/部分，#导致的从这里截断了

**Comment by Hansanshi** [comment]
不了解，我用的是nginx，你看下caddy的文档吧

**Comment by jxjxjhjh** [comment]
收到。
顺便问一下，之前你去编辑器提问大纲固定的问题，开发者说把编辑器高度固定也能有同样的效果，我想想觉的是对的。
下一版本能把编辑器高度固定一下吗？这样就可以保持大纲不会被拉上去了。

**Comment by jxjxjhjh** [comment]
> 不了解，我用的是nginx，你看下caddy的文档吧

设置没问题，是地址中出现了#号，能优化一下去掉#号吗？

**Comment by Hansanshi** [comment]
Nginx配置跳转没问题，那这明显是caddy的问题或者你配置的问题

**Comment by jxjxjhjh** [comment]
> Nginx配置跳转没问题，那这明显是caddy的问题或者你配置的问题

mail.191954.xyz 这个跳转就没问题啊，同样的配置到公开笔记就不行，当时nginx又能跳转公开笔记，能想到的原因就只有跳转域名中那个 /#/ 在caddy中不支持的原因了

**Comment by jxjxjhjh** [comment]
> Nginx配置跳转没问题，那这明显是caddy的问题或者你配置的问题

配置没问题，我现在设置跳转到baidu.com可以正常访问。
实际上就是caddy跳转不支持域名中有#号。

**Comment by Hansanshi** [comment]
所以这就是caddy的问题嘛   应该caddy改

因为这本质是一个单页应用，有#是正常的，历史模式是需要后端进行配合配置
