### ISSUE TITLE
大纲条目字数多的话会往左偏移

### ISSUE THREAD

**Issue by jxjxjhjh** [Hansanshi/mark-idea#13]
大纲条目字数多的话会往左偏移，导致同级条目无法左对齐，同时右边超出，不会换行。
如图
![Screenshot 2021-01-06 13.51.00.png](https://i.loli.net/2021/01/06/lNki5gFUYC7aoWA.png)

**Comment by Hansanshi** [comment]
这个是vditor的问题  到那边反馈吧
