### ISSUE TITLE
新版本好用，撒花

### ISSUE THREAD

**Issue by jxjxjhjh** [Hansanshi/mark-idea#14]
对于写长文来说，至少在电脑上进入可用的程度了。
提一下另外几个问题，不过我也没想到好的解决办法，先提一下看看。
1、手机浏览器，打不开大纲，所以使用不方便的问题还存在，倒是有可参考的实现方式，但是因为用的是vditor，这个功能不知道是不是能够实现：在顶部左上角或右上角固定一个浮动按钮，点击打开大纲，就像github的页面设计一样，你用手机浏览器打开github就能看到，左上角有一个三条横杠按钮。
2、批量替换功能有需要，可能需要vditor编辑器增加吧。
3、0.4.3版本的大纲样式有点问题，往下滚动页面，大纲固定之后最上面一条看不到。

**Comment by Hansanshi** [comment]
1. 试了下  是vditor限制了 因为手机浏览器宽度不够   如果横屏的话  是能够展示大纲的。要解决的话  需要研究下
2. 这个需要vditor添加
3. 最上面一条实际就是“大纲”两个字，实际标题都看得到
