### ISSUE TITLE
手机浏览器如何实现Ctrl+z后退功能？

### ISSUE THREAD

**Issue by jxjxjhjh** [Hansanshi/mark-idea#15]
刚才编辑一个文件，不知道哪儿按错了把内容给全删除了，本来在电脑上Ctrl+z就能回退找回内容的，偏偏手机上无法实现，希望能增加这个功能。

**Comment by Hansanshi** [comment]
下个版本加上按钮，之前没太关注过手机端的使用

**Comment by Hansanshi** [comment]
@jxjxjhjh 见上
