### ISSUE TITLE
年前还有更新吗？

### ISSUE THREAD

**Issue by jxjxjhjh** [Hansanshi/mark-idea#17]
下个版本什么时候发？等得心焦。

**Comment by Hansanshi** [comment]
或许这周或者下周  年前最后一个版本了

我这边只是业余时间抽空做   又没有其他人协助  所以更新不会很快   不太重要合理又很麻烦的也不大会去做  

新版本的主要更新是UI优化、网站初级个性化设置（网站标题、最大文件上传大小等）

**Comment by jxjxjhjh** [comment]
> 或许这周或者下周 年前最后一个版本了
> 
> 我这边只是业余时间抽空做 又没有其他人协助 所以更新不会很快 不太重要合理又很麻烦的也不大会去做
> 
> 新版本的主要更新是UI优化、网站初级个性化设置（网站标题、最大文件上传大小等）

后台功能其实已经足够了，就是想要前端自定义优化的设定。
昨天我自己改了两处css，进vps用vi改的
比较麻烦。

感谢，业余爱好有空再做不用急。

**Comment by jxjxjhjh** [comment]
对了，反馈个问题
刚换了个小众的浏览器，其他网站都能识别账号密码框，记住并自动填充，但mi不行，是不是标识代码不够严谨？

**Comment by Hansanshi** [comment]
应该不是  按照elementUI标准写法写的
