### ISSUE TITLE
建议增加webdav功能。

### ISSUE THREAD

**Issue by jxjxjhjh** [Hansanshi/mark-idea#2]
只有git这一种备份还是有些单薄了吧，希望能增加webdav功能，而且希望不只是用来做备份，而是可以直接把webdav空间当成根目录。
例如webdav中的文件夹就是笔记本，单个文件就是笔记。
这本身就是mi保存文件的结构，实现起来没有根本性的困难。
希望能采纳。

**Comment by Hansanshi** [comment]
@jxjxjhjh 
用webdav作备份是可以的，不过相对git备份就麻烦了点（实际就是关联远程再push下，后期有空在考虑，最近在开发其他），但是直接用webdav空间作根目录，就会没有版本控制的功能了，这个不是很好了。

**Comment by jxjxjhjh** [comment]
现在用的是docker映射到私有云根目录，解决了同步和版本控制问题。
webdav的版本控制功能可以通过定时上传备份实现（我私有云就是这个原理，每次上传就做一个备份）
