### ISSUE TITLE
保存后有提醒反馈

### ISSUE THREAD

**Issue by joywqy** [Hansanshi/mark-idea#20]
文章写好后，ctrl+s 后可否有保存成功提醒

**Comment by jxjxjhjh** [comment]
> 文章写好后，ctrl+s 后可否有保存成功提醒

临时解决方案是多空一格，保存了就会自动清楚掉空格，就知道了。

**Comment by Hansanshi** [comment]
没有加弹窗  单纯是怕保存过多  弹窗过多  比较烦

不过是可以考虑其他形式来展现

现在要判断也很简单，直接点击另一个笔记或笔记本，如果没有保存成功，切换时会提醒你的

**Comment by Hansanshi** [comment]
会展示个已编辑状态 如果内容发生改变。保存了就不会
