### ISSUE TITLE
登录状态记不住？

### ISSUE THREAD

**Issue by jxjxjhjh** [Hansanshi/mark-idea#21]
还是和以前一样。
不过不知道是不是我的使用方法不一样造成的。
你可以去看看我那个docker实现方式的代码，是不是那个原因？
但是我又觉得不太可能，毕竟登录状态的记忆应该不会受到影响啊。
本地浏览器应该是没有问题的。

**Comment by Hansanshi** [comment]
是个bug   下个版本修复

**Comment by Hansanshi** [comment]
先看看新版本  没测试

**Comment by jxjxjhjh** [comment]
终于等到更新，测试好来给反馈😇

**Comment by jxjxjhjh** [comment]
设定一小时是有效的，设定24小时的时候他就一直不需要重新登录，连着测试了两天都还是登录状态。

**Comment by jxjxjhjh** [comment]
之前是手机浏览器测试结果，PC浏览器测试结果则没问题。
原因不明。

**Comment by Hansanshi** [comment]
那应该没问题，可能手机浏览器后台一直没退出。这个登录时效的含义是距最后一次退出的时间
