### ISSUE TITLE
新版本不读取本地文件，能不能考虑一下

### ISSUE THREAD

**Issue by jxjxjhjh** [Hansanshi/mark-idea#22]
我使用的方式不一样，因为手机上浏览器上优化不好，所以我在手机上用的其他客户端修改文件，但是0.4.4版本后发现不会像以前一样在打开时读取手机上修改过的文件了，开始不知道这个问题，弄丢了好多字。
我是用docker假设了同步程序和markidea，映射文件夹在同一个文件，在电脑上就用浏览器打开markidea，修改后会同步到手机，手机用其他客户端修改，然后同步到vps。
0.4.4的版本打开markidea，文件是最新的（会提示有内容没有保存），但是最新版打开markidea，文件是上一次在markidea中保存的版本（也会提示有内容没有保存），所以如果保存的话，那文件就还是上次的版本，手机上的修改就没了。
就是没法读取手机同步过来的最新版。
不知道能不能兼顾一下我这种使用方式。

另外有个建议，现在手机上都没有好用的markdown客户端，能不能开发一个简易的配套客户端，通过api连接markidea，利用客户端原生功能改变手机上使用浏览器中一些不好用的问题。

**Comment by Hansanshi** [comment]
1. 这个一直有  不能算是bug   markidea有缓存  会优先取缓存中的数据 你这种操作会绕开缓存更新；

2. 简易手机客户端写起来也很麻烦，web端对于业余个人开发是个更好的选择。推荐使用wiznote lite手机端，编辑器体验不错，还可以连接wiznote的服务器（官方或自建都可以）。

**Comment by jxjxjhjh** [comment]
1，能否在以后的更新中增加相关的设置，让我这种使用方法能够使用？
2，wiz就算了，市面上能用的我都试过，总有不合适的，到你这算是遇到了一个基本满足的了，可惜最新版本才出现这个问题，之前的版本好像是没有的，我用的挺好。手机客户端随口一提，没有也没关系。

**Comment by Hansanshi** [comment]
直接重启服务，就会让缓存全部失效，如果不想重启
等12个小时 这个缓存也会失效，这个12小时时长后面可以给个配置项

如果不想重启，也不想等，有2个方法可以绕开  但不保证后面不会改这个逻辑

1. 重命名笔记本，然后再刷新
2. 公开笔记，然后刷新，然后再取消公开这个笔记

**Comment by jxjxjhjh** [comment]
期待12小时配置项，最好能支持到分钟而不是小时。
