### ISSUE TITLE
如何迁移服务后数据能正常保存

### ISSUE THREAD

**Issue by dislazy** [Hansanshi/mark-idea#26]
作者您好：
感谢您开发的这个笔记系统，目前遇到了一个问题，我这边会在很多服务器进行部署该笔记，但是看源代码发现对应的文件都是存在classess文件夹下，如何实现 我迁移后也能正常看到对应的笔记本和内容呢？

**Comment by Hansanshi** [comment]
在classes文件夹下，那是因为你在IDE中启动。
正常jar形式启动，所有相关文件都在同一目录下。
迁移时，直接复制jar所在文件夹所有文件即可。

**Comment by dislazy** [comment]
好的 谢谢 遇到另外一个问题，当前后端分离部署时，设置站点信息会提示找不到对应文件 这块能不能进行优化呢

**Comment by Hansanshi** [comment]
这个是因为修改网站名，实际是修改同一目录下的前端html文件的一段内容，当前后端分离部署时，就会找不到前端文件。

这个场景我考虑下要不要做

**Comment by dislazy** [comment]
对的  可以考虑一下
