### ISSUE TITLE
保存后，光标停留在编辑状态的位置

### ISSUE THREAD

**Issue by derek964** [Hansanshi/mark-idea#29]
当前表现：正文编辑保存后，光标会跳到页面头部的位置
期望：保存后，光标保持在编辑状态时的位置，不要回到页面的顶部重新开始。
    方便编辑时候随时ctrl+S，然后接着写。

**Comment by Hansanshi** [comment]
不用随时ctrl + s，笔记每隔10秒会自动保存到服务器的，但不会提交git。

光标会变的原因比较复杂，解释起来比较麻烦，而且当时还要考虑代码实现的简便。

但最初的根源是编辑器vditor会自动吞掉空行 所以我不得不在保存时进行重新设置。
