### ISSUE TITLE
移动端浏览器无法使用，需要做响应式设计

### ISSUE THREAD

**Issue by jxjxjhjh** [Hansanshi/mark-idea#3]
移动端浏览器打开看不到右边的编辑器，左边的侧栏又无法隐藏。

**Comment by Hansanshi** [comment]
@jxjxjhjh 
左边的侧栏是可以隐藏，点击左上角的`MarkIdea`字样即可。后续可能再考虑下移动端的优化

**Comment by jxjxjhjh** [comment]
原来如此，会了。
不过还有问题，1 手机浏览器隐藏侧栏后也打不开大纲功能。2 任何界面大纲功能都现实不正常，样式有问题。3 希望编辑器工具栏和大纲都能固定在浏览器某个位置，而不是下滑内容后就看不到了。

**Comment by Hansanshi** [comment]
1. 竖屏确实不可以，但横屏是可以的，竖屏宽度不够
2. 哪儿不正常，我没发现
3. 这个工具栏固定我研究下  使用的编辑器是支持的

**Comment by jxjxjhjh** [comment]
> 1. 竖屏确实不可以，但横屏是可以的，竖屏宽度不够
> 2. 哪儿不正常，我没发现
> 3. 这个工具栏固定我研究下  使用的编辑器是支持的

![FireShot Capture 003 - MarkIdea 笔记 - note.191954.xyz.png](https://i.loli.net/2020/12/22/7SdlrijkZuCJB2O.png)

**Comment by Hansanshi** [comment]
@jxjxjhjh 
工具栏已经可以[固定](https://github.com/Hansanshi/mark-idea-front/commit/8a630b9acd86ce0539e60ebea8db6cd3ebd48ab5)，大纲固定需要等编辑器
