### ISSUE TITLE
笔记本中的笔记排序逻辑问题

### ISSUE THREAD

**Issue by derek964** [Hansanshi/mark-idea#31]
同一个笔记本下的笔记排序好像没有顺序规律，
既不是最近更新，也不是按照拼音首字母，建议这里可以有个排序逻辑
![image](https://user-images.githubusercontent.com/33562210/130377852-0580b47d-e8ed-45e1-a28c-6496e5970890.png)

**Comment by Hansanshi** [comment]
我是按最近更新时间排序的

**Comment by derek964** [comment]
奇怪了～～我再观察观察
