### ISSUE TITLE
希望增加一个子笔记本的功能

### ISSUE THREAD

**Issue by Catl07** [Hansanshi/mark-idea#32]
希望能够和在笔记本下增加一个子笔记的功能
![image](https://user-images.githubusercontent.com/51349841/132096474-9dafd8b4-14d5-4449-9211-e5b9699ac6a8.png)

**Comment by Catl07** [comment]
另外历史版本还希望可以预览一下，这样能够确定这个版本是不是需要的版本

**Comment by Hansanshi** [comment]
增加子笔记本 这个改动有点大   预览这个要研究下 如果底层库不支持就没办法了

**Comment by zimtsui** [comment]
确实，没层级目录是硬伤

**Comment by Hansanshi** [comment]
@Catl07  已初步支持历史预览   子级目录与现有逻辑冲突太厉害  暂时不考虑

**Comment by Catl07** [comment]
您好，您的邮件我已经收到，现在在忙，不能及时回复您，稍后会查看并回复您的邮件，望见谅！
