### ISSUE TITLE
中文乱码

### ISSUE THREAD

**Issue by keuin** [Hansanshi/mark-idea#34]
笔记里如果写有中文，刷新页面后会变成乱码。

Java环境：
openjdk version "16.0.2" 2021-07-20
OpenJDK Runtime Environment (build 16.0.2+7)
OpenJDK 64-Bit Server VM (build 16.0.2+7, mixed mode)

系统是Archlinux，内核是5.14.6-arch1-1

**Comment by Hansanshi** [comment]
你发个截图来看看，按道理不应该问题的   demo网站也是跑在linux（不过是centos7 jdk8）中 也没出现什么乱码错误  

你还可以F12打开网络页面 查看下接口响应有无问题

**Comment by keuin** [comment]
![image](https://user-images.githubusercontent.com/9404034/134490791-211c0e14-e6ce-4588-95b9-c3a7577a79cd.png)

保存上述内容后，会有一个POST请求把文本传到服务器：

![image](https://user-images.githubusercontent.com/9404034/134490845-67e18513-63a4-49a7-9154-312ab76ab7ef.png)

响应是success，但是在服务器上会被保存成ASCII问号：

![image](https://user-images.githubusercontent.com/9404034/134491617-ed59a14b-568c-41a3-90b6-eab4df09bad6.png)

忘记说了，我用了Nginx作为反向代理来提供SSL支持，无论是否用`charset utf-8`来强制指定编码为`utf-8`，都会出现这样的情况。

这是我的Nginx配置文件：

![image](https://user-images.githubusercontent.com/9404034/134492115-c638d642-e35e-4398-ba61-7224cd43612a.png)

换成java8也是一样，版本是：

```
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (build 1.8.0_292-b10)
OpenJDK 64-Bit Server VM (build 25.292-b10, mixed mode)
```

感觉问题可能出在我的Nginx配置上，我继续研究一下。
