### ISSUE TITLE
希望不使用git同步的时候不要生成相关文件

### ISSUE THREAD

**Issue by jxjxjhjh** [Hansanshi/mark-idea#5]
因为权限问题，我用的syncthing同步软件无法将其同步到其他设备上。

**Comment by Hansanshi** [comment]
你是说哪个文件  为啥syncthing不能同步  目前这些文件都是需要的

**Comment by jxjxjhjh** [comment]
下列项目无法被同步。 系统将会自动重试，当错误被解决时，它们将会被同步。
.git/HEAD | permission denied
-- | --
.git/branches | permission denied
.git/config | permission denied
.git/hooks | permission denied
.git/objects/00 | directory has been deleted on a remote device but is not empty; the contents are probably ignored on that remote device, but not locally
.git/objects/00/d0ac9e90f7658dd93fe8ff4770ec3e2c9c98a4 | permission denied
.git/objects/01 | directory has been deleted on a remote device but is not empty; the contents are probably ignored on that remote device, but not locally
.git/objects/01/c7144b30216b7320b3e83143a2b6a17c61ff4e | permission denied
.git/objects/01/d03e119cdcb3875e6fa27743fe00b9f54e72bc | permission denied
.git/objects/02 | directory has been deleted on a remote device but is not empty; the contents are probably ignored on that remote device, but not locally

这是一部分，一共400多条全都是.git文件夹中的。

**Comment by jxjxjhjh** [comment]
但是直接创建的笔记是可以同步的，只有.git不能同步，难道这个文件夹中的文件权限不一样？不应该吧？

**Comment by Hansanshi** [comment]
不清楚  我没有设置过文件权限  底层使用的是JGit   你试试给syncthing高一些权限

**Comment by jxjxjhjh** [comment]
markidea和syncthing都是docker容器，mi映射文件路径到主机，syncthing对其进行同步，这种情况下，请问如何给syncthing更高权限？会有用吗？
另外，希望官方能出docker镜像，一旦更新立即构建，现在用别人的镜像，更新的比较佛系。

**Comment by Hansanshi** [comment]
这个docker权限我也不是很清楚  网上搜一下吧 跟这个软件没啥关系

这个后面有空弄一下
