### ISSUE TITLE
公开笔记访问原始网址可以，做跳转就不行，会进入登录界面。

### ISSUE THREAD

**Issue by jxjxjhjh** [Hansanshi/mark-idea#6]
https://note.191954.xyz/#/article/191954/2
这个公开笔记网址可以正常访问，但如果把191954.xyz做跳转到这里就不行。
跳转功能和方法应该是没有问题的，因为另一个跳转网址是正常的。
还是0.4版，docker镜像作者不更新(~ _ ~)
另外，忘记是哪个开源项目了，作者好像是找到了一个办法，把网址中的#号去掉了，你要不要研究下？当然，两个项目可能编程语言都不一样，不一定都能实现，这个不重要，顺口一提而已。

**Comment by Hansanshi** [comment]
没有复现你说的这种跳转异常情况    你最好详细说明下  附上视频或截图或详细视频 （图片不要用github  因为我看不到github上的图片）

**Comment by Hansanshi** [comment]
这个java部署也很简单 也就两行命令

**Comment by jxjxjhjh** [comment]
> 没有复现你说的这种跳转异常情况你最好详细说明下附上视频或截图或详细视频（图片不要用github因为我看不到github上的图片）

？你访问 191954.xyz  可以跳转到 https://note.191954.xyz/#/article/191954/2 ？我这访问是跳转到登录界面了，应该跳转https://note.191954.xyz/#/article/191954/2才对。
另外，vps全用docker保持纯净，还是希望有时间搞个官方docker。

**Comment by Hansanshi** [comment]
你配置错了吧  你配置的是跳转到https://note.191954.xyz/    见图
![https://gitee.com/hansanshi/image/raw/master/20201229212018.png](https://gitee.com/hansanshi/image/raw/master/20201229212018.png)

正确配置如下
![https://gitee.com/hansanshi/image/raw/master/20201229212208.png](https://gitee.com/hansanshi/image/raw/master/20201229212208.png)

你可以复制这个网址  pptvector.sanshicloud.cn   这个跳转没问题
