### ISSUE TITLE
几个建议

### ISSUE THREAD

**Issue by jxjxjhjh** [Hansanshi/mark-idea#7]
1、自动保存：想要定时或连续保存，保证出现任何问题不丢文档，不知道能不能实现，毕竟是web不是客户端。（这个编辑器一保存就丢失焦点，如果做自动保存也得考虑这个问题。（这个是不是需要去编辑器提建议？）
2、编辑器工具栏已经固定位置了，大纲能不能固定位置？写长文比较需要这个，因为要回看某一个部分。
3、一个非常不重要的功能：全局自定义css样式，不知道有没有兴趣加上。

**Comment by Hansanshi** [comment]
1. 编辑器本身就支持自动保存，只不过被我禁用了。不过这种只支持保存在浏览器本地缓存里。另外一种选择是保存在服务器端，这样可以跟着走，实际markidea服务端就有保存草稿的接口和功能，不过感觉实现得不太好，暂时禁用了。后面会再用一种简单方式实现下，但肯定不会自动git commit，这会污染笔记的修改历史。
2. 这个需要编辑器底层支持，自己实现麻烦了点。
3. 这个比较麻烦，对于我来说，暂时没有计划，最好是有比较熟悉前端技术的小伙伴参与。

**Comment by jxjxjhjh** [comment]
> 1. 编辑器本身就支持自动保存，只不过被我禁用了。不过这种只支持保存在浏览器本地缓存里。另外一种选择是保存在服务器端，这样可以跟着走，实际markidea服务端就有保存草稿的接口和功能，不过感觉实现得不太好，暂时禁用了。后面会再用一种简单方式实现下，但肯定不会自动git commit，这会污染笔记的修改历史。
> 2. 这个需要编辑器底层支持，自己实现麻烦了点。
> 3. 这个比较麻烦，对于我来说，暂时没有计划，最好是有比较熟悉前端技术的小伙伴参与。

第二个固定大纲不能像工具栏一样吗？

**Comment by jxjxjhjh** [comment]
> 1. 编辑器本身就支持自动保存，只不过被我禁用了。不过这种只支持保存在浏览器本地缓存里。另外一种选择是保存在服务器端，这样可以跟着走，实际markidea服务端就有保存草稿的接口和功能，不过感觉实现得不太好，暂时禁用了。后面会再用一种简单方式实现下，但肯定不会自动git commit，这会污染笔记的修改历史。
> 2. 这个需要编辑器底层支持，自己实现麻烦了点。
> 3. 这个比较麻烦，对于我来说，暂时没有计划，最好是有比较熟悉前端技术的小伙伴参与。

哈，看到你在编辑器那边提建议了。

**Comment by Hansanshi** [comment]
@jxjxjhjh 
自动保存见 [v0.4.2](https://github.com/Hansanshi/mark-idea/releases/tag/V0.4.2)，笔记若未显式保存有标签展示，后续整个用户手册
