### ISSUE TITLE
创建的笔记本希望能增加修改功能

### ISSUE THREAD

**Issue by joywqy** [Hansanshi/mark-idea#8]
![v2-ecd1f6144d794284a1f8f2bc3c7c9e1f_hd](https://user-images.githubusercontent.com/6856954/103330789-f2471e00-4a9d-11eb-97f3-228b4232e814.png)
以上，谢谢

**Comment by Hansanshi** [comment]
@joywqy 
重命名笔记本见 [v0.4.2](https://github.com/Hansanshi/mark-idea/releases/tag/V0.4.2)
