### ISSUE TITLE
设置界面增加版本号显示吧

### ISSUE THREAD

**Issue by jxjxjhjh** [Hansanshi/mark-idea#9]
0.4.2版本我更新了几次docker版，都没发现有什么变化，又看不到版本号，都不知道是什么情况，希望下一个版本显示下版本号。

**Comment by Hansanshi** [comment]
嗯  下次增加个关于窗口展示版本号

0.4.2主要是支持重命名笔记本（右键笔记本就有重命名选项），自动保存正常编辑的笔记（10秒保存一次，保存到服务器，如果意外退出浏览器，下次再进入，可以看见笔记有一个灰色的感叹号）
